### ISSUE TITLE
Tirar dependências de Mysql

### ISSUE THREAD

**Issue by fernandogrd** [pythonbrasil/pybr2014-site#1]
Basicamente o conector, visto que vamos usar o postgres.

**Comment by gilsondev** [comment]
Aproveitando, poderiamos usar o dj-database-url, para começarmos a usar configurações com variáveis de ambiente.

**Comment by luanfonceca** [comment]
Fala @gilsondev, mas esse problema do Mysql é culpa do Mittun, um cms que no requirements dele tinha esse Mysql.

Mas o dj-database-url seria uma boa, apesar de já estar tudo pronto kkkkkkkkk

**Comment by gilsondev** [comment]
Pois é. Será usado o Mittun futuramente ou não?

**Comment by luanfonceca** [comment]
Num sei, a próxima galera que for fazer que escolha.
Mas seria bom forkar o da pycon...
