### ISSUE TITLE
Atualizar badget e banner no https://www.python.org.br

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/pybr2014-site#13]
Ola, o https://www.python.org.br e http://associacao.python.org.br/ ainda está com o badget e banner da pythonbrasil[9]
Tentei modificar, mas não possuo permissão.

@marcelcaraciolo @osantana @ericof @cadu-leite

**Comment by fernandogrd** [comment]
@renatooliveira Tem acesso?

**Comment by luzfcb** [comment]
pelo menos na pagina da associação o @osantana tem acesso. Sei disso, por causa desse issue que abri e ele resolveu: https://github.com/pythonbrasil/apyb.gerenciamento/issues/66

**Comment by osantana** [comment]
tenho acesso mas não sei trocar :D deixa eu ver se descubro como faz isso...

**Comment by ericof** [comment]
Eu sei trocar. Pode deixar

**Comment by osantana** [comment]
@ericof não sei o que colocar lá também... acho que não finalizaram os banners... acabei de pedir pro @renatooliveira

**Comment by renatooliveira** [comment]
Vou pedir pra a o pessoal agilizar isso!

Valeu!

Renato Oliveira
@_renatooliveira http://twitter.com/_renatooliveira
Labcodes - www.labcodes.com.br

2014-07-04 12:28 GMT-03:00 Osvaldo Santana Neto notifications@github.com:

**Comment by erichideki** [comment]
Gostaria de aproveitar a thread com um pedido.

Gostaria de tirar o pó de diversas coisas que temos na home do python.org.br, porém assim como o Fábio não temos 'poder' para mexer nas páginas principais. Será que isso seria possível?

Atualmente venho acompanhando tanto as novidades como os projetos que estão sendo feitos com Python e acredito que seriam muito válidos que sejam colocados como cases na página.

Abraço!

**Comment by marcelcaraciolo** [comment]
voces tem cadastro ?

http://www.python.org.br/wiki

2014-09-26 12:16 GMT-03:00 Eric Hideki notifications@github.com:

> Gostaria de aproveitar a thread com um pedido.
> 
> Gostaria de tirar o pó de diversas coisas que temos na home do
> python.org.br, porém assim como o Fábio não temos 'poder' para mexer nas
> páginas principais. Será que isso seria possível?
> 
> Atualmente venho acompanhando tanto as novidades como os projetos que
> estão sendo feitos com Python e acredito que seriam muito válidos que sejam
> colocados como cases na página.
> 
> Abraço!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonbrasil/pythonbrasil10/issues/13#issuecomment-56975527
> .

## 

Marcel Pinheiro Caraciolo
M.S.C. Candidate at CIN/UFPE
   http://www.mobideia.com
   http://aimotion.blogspot.com/

**Comment by erichideki** [comment]
Tenho.

erichideki
