### ISSUE TITLE
Leves alterações no frontend

### ISSUE THREAD

**Issue by andreneto** [pythonbrasil/pybr2014-site#14]
Percebi uns detalhes que podem vir a dar um melhor acabamento ao frontend do site.
A primeira coisa que tem gerados feedbacks é o degradê usado na página. Usar uma cor sólida ou até a textura do topo deixa o visual mais clean e profissional.
Prints para exemplificar.
![eww](https://cloud.githubusercontent.com/assets/2223776/3156217/282db962-ead7-11e3-9a76-285e73a6acd3.png)
![better](https://cloud.githubusercontent.com/assets/2223776/3156218/2d77aac2-ead7-11e3-8f95-4667e0e54959.png)

**Comment by renatooliveira** [comment]
+1

Renato Oliveira
@_renatooliveira http://twitter.com/_renatooliveira
Labcodes - www.labcodes.com.br

2014-06-03 1:29 GMT-03:00 andreneto notifications@github.com:

**Comment by luanfonceca** [comment]
:+1:

**Comment by renatooliveira** [comment]
@fernandolins me antenou pra uma coisa. Tem uns triangulos no fundo azul. Prefiro tudo sem os triangulos, deixar só no banner mesmo

**Comment by andreneto** [comment]
@renatooliveira
Sim. Fica ainda mais limpo.
Que tal?
![muchbetter](https://cloud.githubusercontent.com/assets/2223776/3164236/31ff4d36-eb48-11e3-8517-9b1c26e5b648.png)

**Comment by fernandolins** [comment]
André,
Ficou legal mais tem outro detalhe.
Para fazer isso, vai ser preciso mexer no 'special-sponsor-aside grid-35',  pois ele quebra e o caranguejo fica de fora

![captura de tela 2014-06-03 as 15 21 40](https://cloud.githubusercontent.com/assets/1887601/3164664/54782550-eb4c-11e3-9754-3ae625507e37.png)

**Comment by andreneto** [comment]
@fernandolins @renatooliveira 
Alterando a cor de fundo do grid-container e corrigindo poucas coisas fica assim:

![done](https://cloud.githubusercontent.com/assets/2223776/3165465/87136d8c-eb54-11e3-94c5-81b37707d47b.png)
![totallydone](https://cloud.githubusercontent.com/assets/2223776/3165466/8b0e65ea-eb54-11e3-8c15-8c09ef161699.png)

**Comment by luanfonceca** [comment]
Show de bola viu!

**Comment by renatooliveira** [comment]
André, abre um PR com as modificações por favor :)

Renato Oliveira
@_renatooliveira http://twitter.com/_renatooliveira
Labcodes - www.labcodes.com.br
