### ISSUE TITLE
Atualizar Título das Páginas (ainda faz referência à Python Brasil 8)

### ISSUE THREAD

**Issue by arthuralvim** [pythonbrasil/pybr2014-site#19]
Título das páginas ainda faz referência à Python Brasil [8], e essa é a ("bola de rombo") 10. =)

![captura de tela 2014-07-02 as 08 49 56](https://cloud.githubusercontent.com/assets/812020/3455318/3563c954-01df-11e4-902c-6a1dd2057a8a.png)

**Comment by arthuralvim** [comment]
Corrigindo: É só na página de registro mesmo.

**Comment by luzfcb** [comment]
@fernandogrd eu estava pensando em uma solução definitiva, visto que existem pelo menos outras 28 ocorrências que se referem ao numero da edição.

https://github.com/pythonbrasil/pythonbrasil10/search?q=%22+PythonBrasil%5B8%5D%22&type=Code

Comecei a implementar, mas devido a uns problemas aqui no meu trampo ai tive que parar para cuidar deles.

O que fiz até o momento foi:
https://github.com/luzfcb/pythonbrasil10/compare/fix-issue-19

**Comment by fernandogrd** [comment]
Boa solução Fábio!
Eu estava pensando em rodar um sed no projeto, auhaauhahauhauha

Mas assim realmente fica muito melhor

**Comment by luzfcb** [comment]
Acho que nesse final de semana consigo tempo para terminar de implementar isso.

**Comment by renatooliveira** [comment]
Acredito que as próximas conferências deveriam utilizar um site que foi
desenvolvido (e pago) para isso: https://github.com/pinax/symposion

Renato Oliveira
@_renatooliveira http://twitter.com/_renatooliveira
Labcodes - www.labcodes.com.br

2014-07-04 10:12 GMT-03:00 Fábio C. Barrionuevo da Luz <
notifications@github.com>:

**Comment by luzfcb** [comment]
@renatooliveira não conhecia esse, e nem que haviam pago por ele.

**Comment by renatooliveira** [comment]
é um projeto patrocinado pela PSF para criar um site reusável de
conferências.

Renato Oliveira
@_renatooliveira http://twitter.com/_renatooliveira
Labcodes - www.labcodes.com.br

**Comment by renatooliveira** [comment]
@henriquebastos, foi esse que tu falou certo?

Renato Oliveira
@_renatooliveira http://twitter.com/_renatooliveira
Labcodes - www.labcodes.com.br

2014-07-04 10:19 GMT-03:00 Renato Oliveira renatooliveira.cin@gmail.com:

> é um projeto patrocinado pela PSF para criar um site reusável de
> conferências.
> 
> Renato Oliveira
> @_renatooliveira http://twitter.com/_renatooliveira
> Labcodes - www.labcodes.com.br
> 
> On Fri, Jul 4, 2014 at 10:17 AM, Fábio C. Barrionuevo da Luz <

**Comment by luzfcb** [comment]
Conferencia feitas com o Symposion

https://us.pycon.org/2013/
http://nyc2012.pydata.org/
http://events.linuxfoundation.org/events/apachecon-north-america/

Ainda existe suporte comercial pela Eldarion.... embora creio que não necessitemos dele...
http://eldarion.com/symposion/

**Comment by luzfcb** [comment]
template de projeto com o Symposion

https://github.com/pinax/pinax-project-symposion

**Comment by fernandogrd** [comment]
O Symposion é todo internacionalizado (inclusive nas postagens)? Tem suporte as paradas da associação? Sistema de pagamento nacional?
Não acho que o trabalho seria muito diferente se usássemos ele.. talvez até mais

**Comment by luzfcb** [comment]
@fernandogrd @renatooliveira 
outra pagina utilizando PythonBrasil[8], na versão em Ingles: http://2014.pythonbrasil.org.br/accounts/login/?next=/dashboard/proposals/

**Comment by fernandogrd** [comment]
Substitui de todos templates
