### ISSUE TITLE
Criar seção "Hospedagem, Transporte e outras dicas"

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/pybr2014-site#24]
Ola pessoal, não sei se isto já foi pensado ou se já esta sendo feito, mas tenho visto varias perguntas sobre hospedagem na lista PythonBrasil.

Seria bom concentrar algumas informações de forma mais explicita no site, inclusive a informação sobre a agencia oficial do evento, e que ninguém é obrigado a se hospedar no hotel Armação ( recentemente houve uma perguntou na lista se era obrigatório hospedar no Hotel Armação ), informações sobre transporte ( Quais as linhas de ônibus, valores. Taxy) e outras dicas como Refeição (valores), atrações turísticas legais (valores)

`Explicito é melhor que implícito`

**Comment by fernandogrd** [comment]
Vou levantar esse ponto na próxima reunião e atualizo o status quanto a isso.

**Comment by luzfcb** [comment]
Ola novamente, @fernandogrd, também seria bom informar dicas de segurança, como por exemplo, onde é relativamente seguro andar a pé, ou por exemplo, se é seguro ir à pé para o Hotel Armação (o hotel que fiz orçamento, que ficou mais em conta, fica 4.1km de distancia do hotel Armação, bem no centro, onde há vários hotéis/pousadas/hostels etc.)

http://globotv.globo.com/rede-globo/netv-1a-edicao/v/roubos-e-assaltos-constantes-tiram-o-sossego-de-moradores-de-porto-de-galinhas/3376898/

Caso se sintam pouco confortável com esse link publicado aqui, pode deleta-lo

**Comment by fernandogrd** [comment]
Fala Fábio,
Cara, porto de galinhas, perto de Recife, ou qualquer outra capital é uma tranquilidade sem tamanho (porto é uma cidade turística, mas super pequena), então acho que não vai ser problema.
Obviamente que sempre temos que ficar atendos, como por ex, ficar de olho na mochila e no notebook (em São Paulo tivemos problemas com roubo), andar em grupo, principalmente quando tivermos com os computadores a noite, etc.
Acho que não é caso pra ter que colocar no site não, se tivermos alguma informação quanto a algum lugar a se evitar, podemos anunciar no dia mesmo.

**Comment by fernandogrd** [comment]
Ah, outro detalhe é que vamos ter onibus, podemos ver a possibilidade de levar todo mundo pro centro de porto após o evento, vou ver a possibilidade quanto a isso.

**Comment by luzfcb** [comment]
Essa informação sobre ônibus toda a faz diferença. Eu já estava procurando contados de taxy, já que andar 4km com minha esposa as 7h da matina creio que não seja uma opção para ela (se eu for sozinho, realmente não me importo de uma caminhada matinal)...
A agencia oficial me indicou um hotel bem perto do hotel Armação, contudo, o Renato me recomendou ficar no centro de Porto de Galinhas, que suponho que fique aqui: https://www.google.com.br/maps/@-8.5072396,-35.0046178,17z

Estou tentando programar a viagem com um pouco de antecedência, e aproveitar para conhecer um pouco de Porto de Galinhas (outra informação bem útil. Quais locais são legais de visitar, valores, contatos de guias com veículos, e se o pessoal trabalham no Domingo dia 9/11, ou seja, após toda a programação da PyBR10 ....)
Quando pedi orçamento para a agencia oficial, também questionei sobre atrações turísticas, contudo, eles só me passaram sobre a hospedagem (acho que devem ter esquecido. Culpa minha, que não questionei novamente)

**Comment by fernandogrd** [comment]
Vou levar isso pra próxima reunião, eu sei que teremos onibus pra quem é/estiver de Recife, aí tem que ver se não vai bater horários, ou mesmo a questão do uso que não sei como é.

**Comment by luzfcb** [comment]
Tendo ônibus do evento ou não, informações sobre transporte de Recife x
Porto de Galinhas e dentro de Porto de Galinhas também seria ótimo e útil
para os participantes (pelo menos é para mim). Informações sobre atrações
turísticas acessíveis no dia 9/11 seria bem útil para mim.

Em 12 de julho de 2014 00:29, Fernando Rocha notifications@github.com
escreveu:

> Vou levar isso pra próxima reunião, eu sei que teremos onibus pra quem
> é/estiver de Recife, aí tem que ver se não vai bater horários, ou mesmo a
> questão do uso que não sei como é.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonbrasil/pythonbrasil10/issues/24#issuecomment-48801145
> .

## 

Fábio C. Barrionuevo da Luz
Acadêmico de Sistemas de Informação na Faculdade Católica do Tocantins -
FACTO
Palmas - Tocantins - Brasil - América do Sul

http://pythonclub.com.br/

Blog colaborativo sobre Python e tecnologias Relacionadas, mantido
totalmente no https://github.com/pythonclub/pythonclub.github.io .

Todos são livres para publicar. É só fazer fork, escrever sua postagem e
mandar o pull-request. Leia mais sobre como publicar em README.md e
contributing.md.
Regra básica de postagem:
"Você" acha interessante? É útil para "você"? Pode ser utilizado com Python
ou é útil para quem usa Python? Está esperando o que? Publica logo, que
estou louco para ler...

**Comment by fernandogrd** [comment]
Fala @luzfcb,
Desculpa a demora para dar a resposta, levantei alguns pontos daqui na última reunião.
- Quanto a usar os onibus para levar os partipantes para o centro ou outras regiões de porto só podemos saber bem mais próximo do evento, vai depdender de fatores como: número de onibus, quantidade de pessoas que vai pra recife, entre outros.
- Estamos planejando colocar uma sessão de coisas a fazer no dia 9.

Bom, no geral acho que vai ser bem tranquilo :), vamos nos falando até lá!
