### ISSUE TITLE
Preparar e alterar html/css

### ISSUE THREAD

**Issue by fernandogrd** [pythonbrasil/pybr2014-site#3]
Html base e index.

**Comment by luanfonceca** [comment]
Fala galera, tudo bom? @marcelcaraciolo acabou de enviar pra lista do pybr10 um email com os arquivos anexados, referente ao novo layout do site, seria legal fazer isso antes das issues #4, #5 e #7, já que elas lidam com coisas de front-end, concordam?

**Comment by marcelcaraciolo** [comment]
? o mais critico de todas, inclusive ja queremos por o site no ar ate o fim
deste mes para divulgacao, vamos correr com ela pode ser ?

2014/1/7 Luan Fonseca de Farias notifications@github.com

> Fala galera, tudo bom? @marcelcaraciolohttps://github.com/marcelcaracioloacabou de enviar pra lista do pybr10 um email com os arquivos anexados,
> referente ao novo layout do site, seria legal fazer isso antes das issues
> #4 https://github.com/pythonbrasil/pythonbrasil10/issues/4, #5https://github.com/pythonbrasil/pythonbrasil10/issues/5e
> #7 https://github.com/pythonbrasil/pythonbrasil10/issues/7, j? que elas
> lidam com coisas de front-end, concordam?
> 
> ?
> Reply to this email directly or view it on GitHubhttps://github.com/pythonbrasil/pythonbrasil10/issues/3#issuecomment-31797083
> .

## 

Marcel Pinheiro Caraciolo
M.S.C. Candidate at CIN/UFPE
   http://www.mobideia.com
   http://aimotion.blogspot.com/

**Comment by fernandogrd** [comment]
Iniciei o processo

**Comment by luanfonceca** [comment]
Massa, quiser abrir um _branch_ e ir commitando pode ficar mais fácil pra gente ajudar. \o/

**Comment by fernandogrd** [comment]
Criei uma branch:
https://github.com/pythonbrasil/pythonbrasil10/tree/new_layout

Passei o css e fiz o base e o home, falta ajustar links, traduções e as outras páginas

**Comment by luanfonceca** [comment]
Alguém me põe na organization da pybr, to precisando das permissão de push/pull ai \o/

**Comment by luanfonceca** [comment]
Pra fazer a internacionalização, eu tive que forkar o Mittun, pois houveram umas mudanças na parte do código da lingua inglesa, que antes era `en-us` e agora é só `en`, então ficava dando um KeyError... Ai quando vocês atualizarem seus códigos, pois tem migrações nos campos gerados pela app `transmeta`:

``` shell
# também coloquei no requirements.txt
$ pip install -e git+git://github.com/luanfonceca/mittun.git#egg=mittun
# remova o banco e depois rode o make setup
$ rm pythonbrasil8/pythonbrasil8.sqlite3 # caso não tenha alterado
$ make setup
```
