### ISSUE TITLE
Alterar informações estáticas

### ISSUE THREAD

**Issue by fernandogrd** [pythonbrasil/pybr2014-site#5]

**Comment by luanfonceca** [comment]
Informações estáticas que estão nos templates? 
Tipo as Datas erradas, Locais... Tipo isso?!

**Comment by fernandogrd** [comment]
Exato, tudo que for estático e tiver que atualizar pra 2014

**Comment by gilsondev** [comment]
Todas essas alterações já estão no ambiente de staging?

**Comment by luanfonceca** [comment]
Creio que já estejam na produção Gilson, os que eu criei tendo em base coisas que tinham de ser feitas, eu terminei:

luanfonceca referenced this issue 2 months ago Closed
Issue #9: Fade in/out nas Bandeiras.
 Luan Fonseca de Fariasluanfonceca referenced this issue 2 months ago Closed
Issue #10: Adicionar sub-título na logo da python brasil
 Luan Fonseca de Fariasluanfonceca referenced this issue 2 months ago Closed
Issue #11: Corrigir links de "Become a sponsor"
 Luan Fonseca de Fariasluanfonceca referenced this issue 2 months ago Closed
Issue #12: Corrigir botões de Facebook e Twitter

**Comment by gilsondev** [comment]
Tem como me dar permissão para subir algumas melhorias?

**Comment by fernandogrd** [comment]
Opa @gilsondev, podemos, mas acho que é melhor usarmos pull requests

**Comment by gilsondev** [comment]
Tranquilo :+1:
